[package]
name = "tna_collect"
version = "0.1.0"
edition = "2021"

[dependencies]
gnss_preprocess = { path = "../../lib" }
rinex = {git = "https://mirror.ghproxy.com/https://github.com/cokkiy/rinex",branch="main" }
csv = "1.3"
